server:
  port: 9522
#  port: 9999
spring:
  kafka:
    bootstrap-servers: ${KAFKA_URL}
    consumer:
      group-id: chat-group
      auto-offset-reset: earliest       # 토픽의 처음부터 읽기
      enable-auto-commit: false          # 오프셋 자동 커밋 비활성화
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: ${CHAT_DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    mongodb:
      uri: ${MONGO_URI}
      database: groupbee


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /api/chat/swagger
  swagger-ui:
    path: /api/chat/swagger