server:
  port: 9999

spring:
  kafka:
    bootstrap-servers: ${KAFKA_URL}
    consumer:
      group-id: chat-group
      auto-offset-reset: earliest       # 토픽의 처음부터 읽기
      enable-auto-commit: false          # 오프셋 자동 커밋 비활성화
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: ${CHAT_DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      jdbc-url: ${CHAT_DATASOURCE_URL}  # HikariCP에서도 인식하도록 설정 (중복되지만 필요)
      maximum-pool-size: 10             # 필요 시 HikariCP 옵션 추가
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      pool-name: HikariPool-1

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      uri: mongodb://100.64.0.11:27017/final
      database: chat

springdoc:
  api-docs:
    path: /api/chat/swagger
  swagger-ui:
    path: /api/chat/swagger